version: 2

builds:
  - id: mailersend
    binary: mailersend
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/mailersend/mailersend-cli/cmd.version={{.Version}}
      - -X github.com/mailersend/mailersend-cli/cmd.commit={{.ShortCommit}}
      - -X github.com/mailersend/mailersend-cli/cmd.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc

homebrew_casks:
  - name: mailersend
    binaries:
      - mailersend
    homepage: "https://github.com/mailersend/mailersend-cli"
    description: "Command-line interface for the MailerSend API"
    directory: Casks
    repository:
      owner: mailersend
      name: mailersend-cli
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
