# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailersend" do
  name "mailersend"
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailersend"

  on_macos do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "064e77c8d0268ddf730f1d8d6082b73efc2fcb616a9ee8f4a165c32ad7311a66"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "bfbb71fa92c060c210b05690021b44a642a6f87b5c077ee1c20b2f8f79ace038"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "c0931c7fd34fca791020d8ccda3eb2c287fcb3aee77ac833e8746225adcf50aa"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "75eaf7cd4f8b4f51db500be10c18d7efdfabc54c78f2634f70c03419371f9a88"
    end
  end

  # No zap stanza required
end
