# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailersend" do
  name "mailersend"
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailersend"

  on_macos do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "3d0266471029bbefce30ff50b27c2d12b3c963f7e51c3ba4b8154491e8b29381"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "155174ab040e8ce221a68b15f8a5df408c12afbcd6a9390f29edae998132bc04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "5fb46a09b797a1a4d0a27466a257a309e9bc58b1ede84df5f9d8dfc4b93ac848"
    end
    on_arm do
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "65581d0659cc53e4eefee65fb99e77a5b69746fa5928df31a061f7202c6c33b2"
    end
  end

  # No zap stanza required
end
