# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailersend < Formula
  desc "Command-line interface for the MailerSend API"
  homepage "https://github.com/mailersend/mailersend-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "064e77c8d0268ddf730f1d8d6082b73efc2fcb616a9ee8f4a165c32ad7311a66"

      def install
        bin.install "mailersend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "bfbb71fa92c060c210b05690021b44a642a6f87b5c077ee1c20b2f8f79ace038"

      def install
        bin.install "mailersend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_amd64.tar.gz"
      sha256 "c0931c7fd34fca791020d8ccda3eb2c287fcb3aee77ac833e8746225adcf50aa"
      def install
        bin.install "mailersend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailersend/mailersend-cli/releases/download/v#{version}/mailersend-cli_#{version}_linux_arm64.tar.gz"
      sha256 "75eaf7cd4f8b4f51db500be10c18d7efdfabc54c78f2634f70c03419371f9a88"
      def install
        bin.install "mailersend"
      end
    end
  end

  test do
    system "#{bin}/mailersend", "version"
  end
end
